name: Haskell tag
description: Creates a tag based on Haskell package version, if missing
inputs:
  package-yaml:
    description: "Path to package.yaml for reading version"
    required: true
    default: ./package.yaml
  tag-prefix:
    description: "Prefix for tags, default is v"
    required: true
    default: v
outputs:
  tag:
    description: "Tag, if one was created"
    value: ${{ steps.run.outputs.tag }}
runs:
  using: composite
  steps:
    - id: prep
      uses: mikefarah/yq@v4.14.1
      with:
        cmd: yq eval '.version' '${{ inputs.package-yaml }}'

    - id: run
      name: Run
      shell: bash
      run: |
        ${{ github.action_path }}/bin/run \
          -r "${{ github.repository }}" \
          -c "${{ github.sha }}" \
          -t "${{ inputs.tag-prefix }}${{ steps.prep.outputs.result }}"
